import numpy as np

class CKY:
	def __init__(self, grammar):
		"""
		Initializes the CKY parser with a given Context-Free Grammar (CFG).

		Parameters
		----------
		"""
		self.grammar = grammar

	def set_grammar(self, grammar):
		self.grammar = grammar

	def to_chomsky_normal_form(self):
		"""
		Converts the grammar to Chomsky Normal Form (CNF).
		"""
		pass

	def parse(self, word: str, to_cnf: bool=False) -> bool:
		"""
		Parses a given word using the CKY algorithm.

		Parameters
		----------
		word (str): The word to parse.
		to_cnf (bool): Whether to convert the grammar to Chomsky Normal Form
			before parsing.

		Returns
		-------
		bool
			True if the word is in the language generated by the grammar, False
			otherwise.
		"""
		pass

